/* Generated by AN DISI Unibo */ 
package it.unibo.pong

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Pong ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		  val MAXCOUNT= 5
				var COUNT = 0
				
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name STARTS")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleRequest",cond=whenRequest("gamestart"))
				}	 
				state("handleDispatch") { //this:State
					action { //it:State
						updateResourceRep( "short($name)"  
						)
						if( checkMsgContent( Term.createTerm("shot(D)"), Term.createTerm("shot(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								delay(500) 
								CommUtils.outblue("$name received shot from ${payloadArg(0)}")
								 COUNT = COUNT + 1
												
												if(COUNT >= MAXCOUNT){
													System.exit(0);
												}	
								forward("shot", "shot(NAME)" ,"ping" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="handleDispatch",cond=whenDispatch("shot"))
					transition(edgeName="t02",targetState="win",cond=whenDispatch("short"))
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						updateResourceRep( "short($name)"  
						)
						delay(200) 
						if( checkMsgContent( Term.createTerm("gamestart(D)"), Term.createTerm("gamestart(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								answer("gamestart", "gamestartack", "ack(${payloadArg(0)})"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="handleDispatch",cond=whenDispatch("shot"))
				}	 
				state("win") { //this:State
					action { //it:State
						CommUtils.outred("$name HO PERSO!")
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
