/* Generated by AN DISI Unibo */ 
package it.unibo.ping

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Ping ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var N = -1 ; val TMAX = 1000L  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(200) 
						CommUtils.outmagenta("$name started")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="starting",cond=whenEvent("startgame"))
				}	 
				state("starting") { //this:State
					action { //it:State
						CommUtils.outred("$name game STARTS")
						delay(500) 
						 N = 1  
						CommUtils.outblue("$name sends $N  ")
						updateResourceRep( "ballview($N)"  
						)
						forward("ball", "ball($N)" ,"pong" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="receive", cond=doswitch() )
				}	 
				state("receive") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_receive", 
				 	 					  scope, context!!, "local_tout_"+name+"_receive", TMAX )  //OCT2023
					}	 	 
					 transition(edgeName="t01",targetState="endofexchange",cond=whenTimeout("local_tout_"+name+"_receive"))   
					transition(edgeName="t02",targetState="reply",cond=whenDispatch("ball"))
				}	 
				state("reply") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("ball(D)"), Term.createTerm("ball(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 N = payloadArg(0).toInt() 
								 N = N + 1  
								if(  N < 12  
								 ){delay(100) 
								CommUtils.outblue("$name sends $N")
								updateResourceRep("ballview($N)" 
								)
								forward("ball", "ball($N)" ,"pong" ) 
								}
								else
								 {CommUtils.outblack("$name MISS!")
								  N = 1  
								 emit("miss", "miss($N)" ) 
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="receive", cond=doswitch() )
				}	 
				state("endofexchange") { //this:State
					action { //it:State
						CommUtils.outgreen("$name ENDS ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="endgame",cond=whenEvent("endgame"))
				}	 
				state("endgame") { //this:State
					action { //it:State
						CommUtils.outblack("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("end(V)"), Term.createTerm("end(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val X = payloadArg(0).toInt()  
								if(  X == 0  
								 ){CommUtils.outmagenta("$name ho VINTO")
								}
								else
								 {CommUtils.outmagenta("$name ho PERSO")
								 }
						}
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
