/* Generated by AN DISI Unibo */ 
package it.unibo.provider

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Provider ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("sono $name")
						delay(100) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleCalc",cond=whenRequest("calculate"))
				}	 
				state("handleCalc") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("calculate(N)"), Term.createTerm("calculate(K)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("$name ricevuto calculate(${payloadArg(0)})")
									fun fibonacciUsingRecursion(num: Int): Int {
								    				return if (num <= 1) {
								       				 num
								   					} else {
								       				 fibonacciUsingRecursion(num - 1) + fibonacciUsingRecursion(num - 2)
								   					}
												}
												
												val N = payloadArg(0)
												val R = fibonacciUsingRecursion(N.toInt())
								answer("calculate", "replycalc", "replycalc(${payloadArg(0)},$R)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t11",targetState="handleCalc",cond=whenRequest("calculate"))
				}	 
			}
		}
} 
