/* Generated by AN DISI Unibo */ 
package it.unibo.producer

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Producer ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("Sono il $name")
						delay(500) 
						
									var X = "39"
						CommUtils.outblack("$name: sending request with $X")
						request("req", "requesting($X)" ,"consumer" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="handleResponse",cond=whenReply("replied"))
				}	 
				state("handleResponse") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("replied(STR)"), Term.createTerm("replied(STR)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outred("$name: received response ${payloadArg(0)}")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
